### ISSUE TITLE
Connect Interfaces to unit tests

### ISSUE THREAD

**Issue by El-minadero** [uofuseismo/ancor#15]
look at the commit https://github.com/uofuseismo/ancor/commit/2b3fd37e163e9c19ae599e8d60e07c808d11ecba and how I connected the interfaces to the unit tests for bandpass. Apply this to all existing unit tests. Note: one unit test class per interface approach (Sample, numpy arr, numpy matrix)

**Comment by El-minadero** [comment]
I'll also add that if you wrote the test, you are responsible for linking it to the appropriate function interface

**Comment by El-minadero** [comment]
for each sample data set, make sure there is a corresponding unit test function that tests it. also add a .txt file which describes how the sample data was prepared, and how you expect it to pass (i.e. the target).

**Comment by mikeswx** [comment]
Great. Thanks for your good suggestion, Kevin.

Hao

Zhang, Hao
Postdoctoral researcher,
Department of Geology and Geophysics,
University of Utah,
Salt Lake City, UT

**Comment by El-minadero** [comment]
Commit 8ff250a4979ed617487f8b4feda1be15f158736e on branch processing-functions has connected its respective interfaces. Feel free to look at the examples there.
